services:
    app.task.manager:
        class: AppBundle\Manager\TaskManager
        arguments:
               - "@=service('doctrine').getManager()"
               - "%app.task.nb_last%"

    app.category.manager:
        class: AppBundle\Manager\CategoryManager
        arguments:
                - "@=service('doctrine').getManager()"
                - "%app.category.nb_last%"

